### ISSUE TITLE
[Issue] MORE_DROPS effect could dupe items

### ISSUE THREAD

**Issue by Shurelia** [GC-spigot/AdvancedEnchantments#1451]
**Describe the bug**
an enchant with MORE_DROPS effect could be used to duplicate an item

**To Reproduce**
A way to reproduce the video
go search for an unarmed zombie, equip an item in their hand, then kill it with weapon + enchant with MORE_DROPS effect, and then voila, you get more drops from the zombie's item drops, and then repeat.

**Screenshots / Video**
i think its not necessary

**Server Information (please complete the following information):**
 - Minecraft Version: Tuinity b150 (1.16.2)
- Plugin Version: 8.0.0-Pre3.0

**Comment by GC-spigot** [comment]
Should be resolved

**Comment by Shurelia** [comment]
> Should be resolved
@GC-spigot 
um sorry for mentioning you but the issue is still persist on the latest update (8.0.0-Pre3.3) (If you put something on zombies or skeletons hand, then after you kill it with MORE_DROPS effect, the items on mob's hand will get duped)
should i open for a new issue or what?
