### ISSUE TITLE
HELD potion effects do not apply when player logs in while holding the item

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#1962]
## Details

**Describe the bug**
When a player is holding an item with a HELD type enchantment that applies potions effects while the item is held, these effects are not applied when the player logs in holding the item, and they must switch to another item and back to get the effects.

**To Reproduce**
Hold an item with a HELD type enchantment that applies a potion effect. It will give the potion effects. Then reconnect, still holding the item when you log back in. The potion effects will not be applied until you switch equipped items.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/acodekuger

**Comment by RulerOfEternity** [comment]
I think I have a small solution, there's a setting in the config: 

> "clear-potion-effects-on-quit: false"

**Comment by Insprill** [comment]
Are you adding the item when the player is offline with some sort of inventory editor plugin? Just holding the item and logging i still had the effect

**Comment by Dakotaa** [comment]
I'm using [MySQLPlayerDataBridge](https://www.spigotmc.org/resources/mysql-player-data-bridge.8117/), which may be what is causingh the issue as it is loading their items back into their inventory when they log in.

**Comment by Insprill** [comment]
I've implemented a possible fix for this in the next update. Please get back if it solves this.

**Comment by Dakotaa** [comment]
Looks like I'm still having the same issue on the latest verison.

**Comment by Insprill** [comment]
The next update will have HELD update 20 ticks after join instead of 5 which should give enough time for inventory plugins to load inventories. We can't add support for every inventory plugin so this is the best it's gonna get.
