### ISSUE TITLE
Not listening to PlayerInteractEvent being cancelled

### ISSUE THREAD

**Issue by snowgears** [GC-spigot/AdvancedEnchantments#1988]
## Details

**Describe the bug**
My plugin Shop cancels the PlayerInteractEvent (at normal priority) but your plugin fires the Unique book opening anyway. The expected behavior is that when another plugin cancels the event, your code in that event should check if the event is cancelled first before running.

**To Reproduce**
Cancel the PlayerInteractEvent via another plugin at normal priority. Your code in that same event will still fire.

**Screenshots / Video**
https://youtu.be/XCf4EzXpxKk?t=244

## Server Information
- N/A

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by WolverStones** [comment]
@Insprill Is it fixed in the version 8.1.7?

**Comment by Insprill** [comment]
should be

**Comment by snowgears** [comment]
This appears to still not be fixed. Tested on Advanced Enchantments version 8.2.7.

https://media4.giphy.com/media/ETtc5gAX94rRiRlqDi/giphy.gif?cid=790b7611dfddb542fbfafd9fdbb4dd24972a518e622a1ed8&rid=giphy.gif&ct=g

**Comment by WolverStones** [comment]
@Insprill Will you be doing any solutions in the near future?

**Comment by Insprill** [comment]
Yes

**Comment by Insprill** [comment]
Fixed in the next update
