### ISSUE TITLE
Issue with REPAIR effect

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#2053]
## Details

**Describe the bug**

The REPAIR effect doesnt work on Elytra and also throws this issue in console a lot (maybe it is to do with the elytra) https://pastebin.com/VfLWhKka AND on top of this, if 1 item in your inventory (it seems) has the repair effect, it works for any items whether it has the custom enchant or not. Here is my custom enchant:

unbreakable:
  display: '%group-color%Unbreakable'
  description: "Tools with this enchant become unbreakable"
  applies-to: 'All'
  type: 'MINING;ATTACK;ATTACK_MOB;DEFENSE;DEFENSE_MOB;ELYTRA_FLY;RIGHT_CLICK;BOW;BOW_MOB'
  group: 'FABLED'
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
    - ALL_AXE
    - ALL_ARMOR
    - ELYTRA
    - BOW
    - CROSSBOW
  levels:
    1:
      effects:
        - 'REPAIR'

**To Reproduce**

Get an item with the custom enchant that has repair effect and watch it not repair the eyltra and work on any item you use

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
https://paste.md-5.net/fikuquzuji
- Server log: 
- If needed, PM

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by JHarris12345** [comment]
You did not fix the 2nd part of the issue where any item in your inventory gets repaired even if it does not have the repair custom enchant on it. Right now Im hitting mobs with an enchanted stone sword and it's acting like it has the repair enchant on it.

This glitch only works if you have something in your inventory with the repair enchant on it, then any item you use will get repaired and become unbreakable
