### ISSUE TITLE
TP_DROPS Still damages axes, pickaxes, shovels when breaking crops, and now doesn't reward mcMMO harbalism experience

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#2126]
## Details

**Describe the bug**
TP_DROPS enchantments still damage axes, pickaxes, and shovels when breaking crops (these tools are not damaged without the enchantment). Also, mcMMO herbalism exp is no longer being rewarded for breaking crops with TP_DROPS tools since the latest update which fixed them.

**To Reproduce**
Enchant an axe with a TP_DROPS enchantment, breaking fully grown wheat. The axe will be damaged, and no mcMMO herbalism experience is rewarded.

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/icuzuhifug

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Dakotaa** [comment]
It appears that mcMMO EXP is still not being rewarded in the latest update. Also, the TRENCH effect no longer seems to reward mcMMO exp.
