### ISSUE TITLE
Extra Health Attributes - Causes Constant Error

### ISSUE THREAD

**Issue by itslukemango** [GC-spigot/AdvancedEnchantments#2137]
## Details

**Describe the bug**

https://pastebin.com/26k2XhfZ Unsure what CE causes this but any players that have extra hearts (from attributes on armour) gives this error. It's quite spammy.

**To Reproduce**

Unsure what CE causes it, more than likely an armour one. We're using the default setup.

**Screenshots / Video**

https://pastebin.com/26k2XhfZ

## Server Information
- "/ae plinfo" link: 
- Server log: 
https://paste.md-5.net/tarexucisa
https://mclo.gs/lQI2tyn

**Comment by Insprill** [comment]
Fixed in 8.5.2

**Comment by itslukemango** [comment]
> 
> 
> Fixed in 8.5.2

Can confirm this was not fixed. https://pastebin.com/bJwFgRz3
