### ISSUE TITLE
"not-applyable-with" doesn't work with vanilla enchantments in the enchantment table

### ISSUE THREAD

**Issue by rmalca** [GC-spigot/AdvancedEnchantments#2400]
### Describe the bug

For example, when enchanting on a table of enchantments "smelting" should not come out with silk touch. 

```yml
smelting:
  display: '%group-color%Fundición'
  applies-to: 'Pickaxes and shovels'
  type: 'MINING'
  group: 'SIMPLE'
  settings:
    not-applyable-with:
      - MENDING
      - SILK_TOUCH
      - experience
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 25
      effects:
        - 'SMELT'
        - 'EXP:<random number>0-1</random number>'
```

### How to reproduce

1) Enchant a netherite pickaxe on the enchantment table.
2) Repeat until smelting enchantment come out and silk touch. 

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/3759745/136262680-8d605094-ea4b-42ee-a8d3-3136ee07b6b3.png)

### "/ae plinfo" link

https://paste.md-5.net/jopucilave

**Comment by GC-spigot** [comment]
Fixed

**Comment by rmalca** [comment]
Apparently the problem continues. 

![image](https://user-images.githubusercontent.com/3759745/140405654-b59c598a-cccb-4733-b162-a48f50117af1.png)

```
fundición:
  display: '%group-color%Fundición'
  description: ""
  applies-to: 'Pickaxes and shovels'
  type: 'MINING'
  group: 'SIMPLE'
  settings:
    not-applyable-with:
      - MENDING
      - SILK_TOUCH
      - experiencia
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 25
      effects:
        - 'SMELT'
        - 'EXP:<random number>0-1</random number>'
    2:
      chance: 50
      effects:
        - 'SMELT'
        - 'EXP:<random number>0-1</random number>'
    3:
      chance: 100
      effects:
        - 'SMELT'
        - 'EXP:<random number>0-1</random number>'`

**Comment by rmalca** [comment]
I still have the same problem.

```
fundición:
  display: '%group-color%Fundición'
  description: ""
  applies-to: 'Pickaxes and shovels'
  type: 'MINING'
  group: 'SIMPLE'
  settings:
    not-applyable-with:
      - MENDING
      - SILK_TOUCH
      - experiencia
  applies:
    - ALL_PICKAXE
    - ALL_SPADE
  levels:
    1:
      chance: 25
      effects:
        - 'SMELT'
        - 'EXP:<random number>0-1</random number>'
    2:
      chance: 50
      effects:
        - 'SMELT'
        - 'EXP:<random number>0-1</random number>'
```

![image](https://user-images.githubusercontent.com/3759745/140414899-89b58599-d110-4a9f-a2e5-2595d2432fa5.png)

"/ae plinfo" link

https://paste.md-5.net/edavofeser
