### ISSUE TITLE
Special characters doesn't work on lang file

### ISSUE THREAD

**Issue by austv** [GC-spigot/AdvancedEnchantments#2592]
### Describe the bug

Special characters doesn't work on lang file but do on config messages.

### How to reproduce

1. Use pt-br language.
2. Reproduce any message with special characters, like á, é, ç, ã, õ...

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/66658478/150543946-5c4fb3f2-08f1-4f19-8e5b-9dcd1afb04ca.png)

For some reason, some messages works:
![image](https://user-images.githubusercontent.com/66658478/150544012-0955beec-6804-4b9a-a12b-0d70337d240f.png)

and don't for others, same character
![image](https://user-images.githubusercontent.com/66658478/150544046-0a33302d-8907-4460-9a56-8ced4feba720.png)

### "/ae plinfo" link

https://paste.md-5.net/oqumilitog.css

**Comment by GC-spigot** [comment]
Should be resolved

**Comment by austv** [comment]
Didn't fixed, the problem is on language file, not customcommands.

The problem still the same.
