### ISSUE TITLE
ArmorSet Variable Fix

### ISSUE THREAD

**Issue by Superalex0102** [GC-spigot/AdvancedEnchantments#2997]
### Describe the bug

Hey!
Version: 8.14.2
Events like KILL_MOB doesn't wanna work with ArmorSets, many users reported it, please take your time and fix this issue.

### How to reproduce

-

### "/ae plinfo" link

https://paste.md-5.net/yanikodedi

**Comment by GC-spigot** [comment]
Fixed

**Comment by Superalex0102** [comment]
Still doesn't work, if I kill a mob, the plugin doesn't send the configured message
```
  KILL_MOB:
    chance: 100
    effects:
      - 'MESSAGE:&f&lTest'
```

**Comment by GC-spigot** [comment]
This exact scenario has been tested and is now working perfectly. Try adding %attacker% to it
