### ISSUE TITLE
blockbreak error on console

### ISSUE THREAD

**Issue by kingakis2** [GC-spigot/AdvancedEnchantments#3237]
### Describe the bug

When a block is break this errors appears on console

### How to reproduce

Use the last version and break a block

### "/ae plinfo" link

https://paste.md-5.net/varubojegi

### Server Log

https://mcpaste.io/3017511bad757710

**Comment by GC-spigot** [comment]
Fixed!

**Comment by cynikhavoc** [comment]
Still having this issue after updating to the most recent version
