### ISSUE TITLE
Using Trench and Veinminer will cause double drops

### ISSUE THREAD

**Issue by ArmonicPvP** [GC-spigot/AdvancedEnchantments#3256]
### Describe the bug

Using vein miner and trench on ores will cause the ores to drop twice

### How to reproduce

Enchant with veinminer and trench and break 3 diamond ore. you will get 7 (extra is because of another bug)

### "/ae plinfo" link

https://paste.md-5.net/ixululenel

**Comment by GC-spigot** [comment]
Fixed

**Comment by cynikhavoc** [comment]
This issue still persists, however its just trench that does it, with ore blocks you get double blocks, on latest version.

**Comment by cynikhavoc** [comment]
@GC-spigot
