### ISSUE TITLE
TP_DROPS does not give mcMMO EXP

### ISSUE THREAD

**Issue by Dakotaa** [GC-spigot/AdvancedEnchantments#3280]
### Describe the bug

No mcMMO EXP for any skill is given when using a TP_DROPS tool.

### How to reproduce

Enchant a tool with a TP_DROPS enchant.
Break a log, stone, crop, etc.
No mcMMO EXP for the respective skill is rewarded

### "/ae plinfo" link

https://paste.md-5.net/xekamiqive

**Comment by GC-spigot** [comment]
Resolved

**Comment by Dakotaa** [comment]
This still appears to be in the latest version. Tested with only AE and mcMMO installed, and TP_DROPS tools still give no mcMMO EXP.
