### ISSUE TITLE
Dupe bug with Multiplication and Trench

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3325]
### Describe the bug

You need a trench and multiplication with any kind of ore, in order to work with multiplication.

### How to reproduce

1st. Get CE of Multiplication and Trench
2nd. Put it on Pickaxe
3rd. Place Ore and place a shulker box at the top of the ore
4th. Break the Ore with your Pickaxe.
5th. Redo 3rd to 4th step until you dupe the shulker box

### Screenshots / Videos

https://imgur.com/a/YVw5Ir2

### "/ae plinfo" link

https://paste.md-5.net/ucoliganoh

**Comment by GC-spigot** [comment]
I believe this is now fixed, it was an issue with mcmmo

**Comment by KingCueio** [comment]
https://imgur.com/a/S3u3aEt

![image](https://user-images.githubusercontent.com/87959487/236921935-a3a38b06-342a-4cba-a445-fbf59b0dfb0b.png)



https://paste.md-5.net/qeqacahuke


This still happens to me, idk why.
