### ISSUE TITLE
urgent inventory dupe

### ISSUE THREAD

**Issue by aaa8881** [GC-spigot/AdvancedEnchantments#3360]
### Describe the bug

dupe from alchemist 

### How to reproduce

1. install https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next
2. sort by column in /alchemist gui

### Screenshots / Videos

https://imgur.com/a/twA0EhC

### "/ae plinfo" link

https://paste.md-5.net/exisewayes

**Comment by GC-spigot** [comment]
That version of AE is not supported, update to latest - this issue is already fixed on those versions...

**Comment by aaa8881** [comment]
> 

no GC, I tried with latest AE, 9.1.4. that was first thing I tried , and issue still persists.

**Comment by GC-spigot** [comment]
> > 
> 
> no GC, I tried with latest AE, 9.1.4. that was first thing I tried , and issue still persists.

That's the thing, I did try it just now on 9.1.4 and cannot recreate it. I will look at it again, maybe try something else different and let you know if I find the issue.
