### ISSUE TITLE
AXE with timber enchant after breaking chest doesn't drop anything

### ISSUE THREAD

**Issue by DarrienZ** [GC-spigot/AdvancedEnchantments#3627]
### Describe the bug

After breaking the chest with Timber enchantment on the AXE. Items that inside the chest will disappear.

### How to reproduce

This happen after updating the plugin to lastest update

### Screenshots / Videos

https://youtu.be/KVhpRnc3-Ok

### "/ae plinfo" link

https://paste.md-5.net/ripehugepi

### Server Log

https://pastebin.com/Q5p1k4Ln

**Comment by Xyaafol** [comment]
Confirmed that this happens with all 'MINING' type enchantments - like Timer and Reforged

**Comment by DarrienZ** [comment]
Pickaxe too. That item from SlimeFun
https://youtu.be/FAlEHb9TeHw

**Comment by Xyaafol** [comment]
This is also causing a duplication issue, if a player has an item with any of these types of enchantment on a pickaxe in their offhand it will double all drops.

**Comment by Xyaafol** [comment]
Reverting to version 9.3.14 temporarily seems to fix this issue

**Comment by DarrienZ** [comment]
I think you haven't read the SlimeFun one?

**Comment by Xyaafol** [comment]
Please revisit this issue, still broken on 9.3.17 - see video here: https://youtu.be/ggqmAvHC2i0

Tested on a completely fresh server, no other plugins, new install folder of AE, latest AE and Paper version

plink from the footage is https://paste.md-5.net/aribugizef

**Comment by Rexmen1** [comment]
yep same exact issue on my server with some of the enchants...

**Comment by GC-spigot** [comment]
Fixed

**Comment by Rexmen1** [comment]
Not fixed still for me, Which version fixes it? 9.3.17 using it

**Comment by DarrienZ** [comment]
Same

**Comment by Rexmen1** [comment]
and tested with version 9.3.19 

Seems like dev is just closing reports even without testing... and not even small issues but big issues like these where all of the items from chests are gone, duping issues with soulbound which is happening for over a month now...
Please please fix these issues...

**Comment by ThomasWega** [comment]
It will be fixed in the next version...
