### ISSUE TITLE
AOE mobs target ignored protection checks

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#3787]
### Describe the bug

this enchantment does not respect griefPrevention protection 

Immolation
Set all mobs in radius on fire.
Swords
Ultimate

plummet
Deal damage to nearby mobs when taking fall damage.
Boots
Ultimate

for example the kill-aura enchantment that damages the mobs around it respects the protection while these 2 do not

### How to reproduce

use these enchantments inside a region protected by griefPrevention and you'll be able to kill protected animals

### "/ae plinfo" link

https://paste.md-5.net/uqufurepan

**Comment by ThomasWega** [comment]
Should be fixed in the update!

**Comment by SrMonsterYT** [comment]
problem still occurs

https://prnt.sc/6MB2qdkjX7Cu

i can't move that terrain or kill mobs in it, but i can hurt them with this enchantment if there's another mob nearby ( immolation )

https://prnt.sc/Wos9IAwBK6U9

plummet the same thing

**Comment by ThomasWega** [comment]
Obviously... You need to wait for an update

**Comment by SrMonsterYT** [comment]
killaura enchantment not working properly should i open another report?

https://prnt.sc/Cwma_8Jaih5-

only particles come out of the ground and kill only 1 mob

**Comment by SrMonsterYT** [comment]
> Immolation

still happening in version 9.5.10
