### ISSUE TITLE
MENU issues and Holy White Scroll issue

### ISSUE THREAD

**Issue by PengBread** [GC-spigot/AdvancedEnchantments#427]
**Issue #1** 
The show " list of all server enchants " in customcommands.yml doesn't seem to work when set up properly. When clicked on the icon it does not show anything and items can be taken out from the menu.

Also when clicking on tinkerer menu it keep pops out "alchemist not available or something like that in red words ". Not only tinker, it appears on that ^ menu i mention that was not working one too.

**Issue #2**
Holywhitescroll isn't working properly. Players died and items still drop on the floor. No errors etc.
Setting keep-after-death set to true makes the soulbound/holywhitescroll effect not working.

**Comment by GC-spigot** [comment]
Do you have a screenshot /video for the Tinkerer/Alchemist issue?

Fixed 1st & 2nd.

**Comment by PengBread** [comment]
Ignore the Tinkerer/alchemist issue, somehow its not popping anymore. Probably the old version issue as the issue was last seen 2 3 versions before.

**Comment by PengBread** [comment]
Holywhitescroll issue is still not fixed on the latest update. Not sure if the latest ver includes it or not.
