### ISSUE TITLE
Unable to put enchants in anvil 

### ISSUE THREAD

**Issue by DaJMaN4** [GC-spigot/AdvancedEnchantments#4454]
### Describe the bug

Minecraft verison: 1.20.4, 9.9.13 version of the plugin

Cannot put enchant on any item, each time when I try I get errors in the console. 

### How to reproduce

Enable anvil in anvil.yml and config.yml and try to enchant something custom. 

### Screenshots / Videos

![image_2024-07-15_182029272](https://github.com/user-attachments/assets/add4e043-f94c-4836-b95a-1d008b2fbcec)

### "/ae plinfo" link

https://paste.md-5.net/olumedonaq

### Server Log

https://mcpaste.io/83a248a0d80a4714

**Comment by NoltoxGit** [comment]
Yes, I can confirm that this bug still persists.

Here is the command to get the enchanted book I use in my video:
`/aegive Noltox enchanted_book 1 sharpness:3 looting:3 chasseur:1`

https://github.com/user-attachments/assets/aca61e1c-6c90-4051-8dfc-285426dbe2a0

**Comment by ThomasWega** [comment]
Should be fixed in the next update

**Comment by DaJMaN4** [comment]
> Should be fixed in the next update

I still have the same bug, not only when using anvil but also when using drag and drop. 
It might be the case that special characters break the plugin, because in names and description I use them a lot. 
version: https://paste.md-5.net/uqofugavob
