### ISSUE TITLE
[BUG] Can't use the gkit named "Destroyer" and others...

### ISSUE THREAD

**Issue by centerworld2023** [GC-spigot/AdvancedEnchantments#4545]
### Describe the bug

The bug occurs when we want to have a particular gkit (some basic gkits). 

### How to reproduce

Run the /gkit command and select the "Destroyer Kit". 

### Screenshots / Videos

![image](https://github.com/user-attachments/assets/2b5434cd-2aae-4944-b145-ecd9243a78a2)

![image](https://github.com/user-attachments/assets/b3a8c0b0-6edd-4aed-a6bb-46ade1453073)

Error : 

![image](https://github.com/user-attachments/assets/1ecfd1b5-6463-4c05-9d02-c7270d2a936b)

### "/ae plinfo" link

https://paste.md-5.net/amebifozur

### Server Log

https://mcpaste.io/6ec84c12c0f03f20

**Comment by GC-spigot** [comment]
Fixed!

**Comment by centerworld2023** [comment]
Hello,
It's not fixed, because a was update your plugin. I still have the same error with the Destructeur/Destroyer's kit. 

![image](https://github.com/user-attachments/assets/32289c66-7468-495d-999f-d08db66e6625)

Thank you

**Comment by centerworld2023** [comment]
Hello, 

Can you change the ticket to "in progress" instead of "closed"? The problem is still not solved despite the update of the plugin. 
BR 
CenterWorld - Co-founder

**Comment by GC-spigot** [comment]
Regenerate your gkits.yml file :)

**Comment by centerworld2023** [comment]
Can you create a "local" folder every time you install the plugin? 

Every time I have to make a regénération of the plugin files (or an update), I must necessarily redo all the language transfers. This is a considerable work. Eventually, we want to use a specific language pack in one order
(We use the French language). 

The problem for the Destroyer kit is solved, however I see other more or less similar errors with other kits. 

BR 
CenterWorld - Co-Founder

**Comment by centerworld2023** [comment]
Good morning, 
I regenerated as requested the gkit, which fixed only the destroyer kit. I have the same problem with 4 other kits that are now non-functional. 

The names of gkit are as follows: 
Guardian
Valentines
Templar

It is primarily a basic kit. 

Once it is fixed, can you send me the new gkit.yml in French version? 
Thank you

BR
CenterWorld - Co-Founder 

`[17:09:55 INFO]: EnyroxFire issued server command: /gkit
[17:09:57 WARN]: java.lang.IllegalArgumentException: bound must be positive
[17:09:57 WARN]:        at java.base/java.util.Random.nextInt(Random.java:557)
[17:09:57 WARN]:        at java.base/java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:468)
[17:09:57 WARN]:        at AdvancedEnchantments-9.10.4.jar//net.advancedplugins.ae.impl.utils.MathUtils.randomBetween(MathUtils.java:40)
[17:09:57 WARN]:        at AdvancedEnchantments-9.10.4.jar//net.advancedplugins.ae.impl.utils.ASManager.parseEnchantment(ASManager.java:1730)
[17:09:57 WARN]:        at AdvancedEnchantments-9.10.4.jar//net.advancedplugins.ae.impl.utils.items.ConfigItemCreator.fromConfigSection(ConfigItemCreator.java:173)
[17:09:57 WARN]:        at AdvancedEnchantments-9.10.4.jar//net.advancedplugins.ae.impl.utils.items.ConfigItemCreator.fromConfigSection(ConfigItemCreator.java:263)
[17:09:57 WARN]:        at AdvancedEnchantments-9.10.4.jar//net.advancedplugins.ae.features.gkits.GKitBuilder.build(GKitBuilder.java:66)
[17:09:57 WARN]:        at AdvancedEnchantments-9.10.4.jar//net.advancedplugins.ae.features.gkits.GClick.onChooseGKit(GClick.java:67)
[17:09:57 WARN]:        at AdvancedEnchantments-9.10.4.jar//net.advancedplugins.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:26)
[17:09:57 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor750.execute(Unknown Source)
[17:09:57 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[17:09:57 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[17:09:57 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:09:57 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[17:09:57 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[17:09:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[17:09:57 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3119)
[17:09:57 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[17:09:57 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:25)
[17:09:57 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:54)
[17:09:57 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:09:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:149)
[17:09:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[17:09:57 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1465)
[17:09:57 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194)
[17:09:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:123)
[17:09:57 WARN]:        at net.minecraft.server.MinecraftServer.bl(MinecraftServer.java:1442)
[17:09:57 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1365)
[17:09:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:133)
[17:09:57 WARN]:        at net.minecraft.server.MinecraftServer.w_(MinecraftServer.java:1343)
[17:09:57 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1232)
[17:09:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:09:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[17:09:57 INFO]: &cError while building item for kit Templar with item number: 1`

**Comment by centerworld2023** [comment]
Hello, 
What news for my case?
Thank you
BR

**Comment by centerworld2023** [comment]
Hello, 
Please, can you reopen this case? 
Thank you. 
BR

**Comment by ThomasWega** [comment]
Will be fixed in the update!
