### ISSUE TITLE
HELD Trigger BUG

### ISSUE THREAD

**Issue by slyleight** [GC-spigot/AdvancedEnchantments#4590]
### Describe the bug

There is an emergency issue with the HELD trigger. This trigger can be activated without equipping the item, resulting in the strength effect being applied without the item being equipped or even keeping it in your inventory.

> strenght1:
>   display: '%group-color%Strenght'
>   description: '{#770ef8}Kalıcı {#FFC300}Güç {#770ef8}etkisi verir.'
>   applies-to: Kılıç, Balta, Üçlü Mızrak
>   type: HELD
>   group: HEROIC
>   applies:
>   - ALL_SWORD
>   - ALL_AXE
>   - TRIDENT
>   levels:
>     '1':
>       effects:
>       - POTION:INCREASE_DAMAGE:0
>     '2':
>       effects:
>       - POTION:INCREASE_DAMAGE:1
>     '3':
>       effects:
>       - POTION:INCREASE_DAMAGE:2

### How to reproduce

The HELD trigger can be bugged by using mouse clicks other than the main (left) and secondary (right) ones. If you use any other mouse button, the game mistakenly thinks you are equipping the item, when in reality, you're just tricking the game into believing it. Middle mouse wheel clicks and additional side keys on gaming mouse are examples of this. You can see this in the video I provided.

### Screenshots / Videos

https://streamable.com/v0yk44

### "/ae plinfo" link

https://paste.md-5.net/ixiyenobad

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Big thanks for reporting!

**Comment by slyleight** [comment]
Letting you know, the problem still exists after the 9.10.8 update.

**Comment by ThomasWega** [comment]
Yeah it hasn't been merged yet
