### ISSUE TITLE
KEEP ON DEATH - NOT WORKS WITH EXPLOSIVE AND CUSTOM DEATHS

### ISSUE THREAD

**Issue by f4a1led** [GC-spigot/AdvancedEnchantments#4883]
### Describe the bug

Hey!

So we noticed that if the player has an item with Soulbound and dies due to explosion or by any AE made death (Headshot increase dmg, Bleeding ...) the effect KEEP_ON_DEATH won't work.
I've tested it, I made some clips with Medal.

### How to reproduce

Take an item (in my video the Wooden Pickaxe will be that item) enchant it with Soulbound or whatever that has KEEP_ON_DEATH and die with explosion (TNT, Creeper, or AE Explosion) and you will see.
Also the same with any AE made effects like bleeding, headshoot damage multiplier and etc. 

### Screenshots / Videos

1. https://medal.tv/games/minecraft/clips/k5fWSHYNTiHYnXchZ?invite=cr-MSx6aHUsMTg5OTM2ODM1
2. https://medal.tv/games/minecraft/clips/k5g0WLMfrgvYlxXDy?invite=cr-MSx2U2QsMTg5OTM2ODM1

### "/ae plinfo" link

/ae plinfo skipPlugins

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Do you have both DEATH and PASSIVE_DEATH triggers on soulbound?

**Comment by f4a1led** [comment]
> Do you have both DEATH and PASSIVE_DEATH triggers on soulbound?

Sorry for late reply. Yes, of course. Also as I said, we have the newest version.

**Comment by f4a1led** [comment]
We tested it even with region flags and gamerules etc. So explosions, and Custom Enchants killing effects don't work with Soulbound.

**Comment by ThomasWega** [comment]
Can you send me the enchantments you are using in the videos?

**Comment by ThomasWega** [comment]
With creeper explosion it seems to work okay for me. Do note that currently only one soulbound item will be kept if there is a cooldown on the enchantment though. I'm currently handling that

**Comment by f4a1led** [comment]
No cooldowns. I didnt say creeper explosion at all. I mentioned TNT explosions, and AE Enchant's explosion. Please test it with bleeding, and AE's explosion effects. + Vanilla TNT.

**Comment by f4a1led** [comment]
No specific enchants, I made custom exploding bow with your plugin.

**Comment by ThomasWega** [comment]
> No specific enchants, I made custom exploding bow with your plugin.

Well how did you make that bow? I'd like to test with the same setup as you

**Comment by ThomasWega** [comment]
> No cooldowns. I didnt say creeper explosion at all. I mentioned TNT explosions, and AE Enchant's explosion. Please test it with bleeding, and AE's explosion effects. + Vanilla TNT.

My fault. I will retest

**Comment by f4a1led** [comment]
> > No cooldowns. I didnt say creeper explosion at all. I mentioned TNT explosions, and AE Enchant's explosion. Please test it with bleeding, and AE's explosion effects. + Vanilla TNT.
> 
> My fault. I will retest

Oh also new ways: 
We use KingdomsX (so thats a Kingdoms server). And this plugin allows players to place turrets, which shoots arrows, fire projectiles, custom particled projectiles. Now we got a report today that someone died by an Inferno tower (continous damage) and he also lost his item with Soulbound.

**Comment by f4a1led** [comment]
Also I know suggestions and ideas not ment to be sent there. But its realted to Soulbound. My players actually have a nice idea about it. It should has Usage limit. Like you can die with a soulbound enchanted items 3 or 5 items or whatever I give in the config, so after that it gets disenchanted.

**Comment by f4a1led** [comment]
@ThomasWega 
Sorry for ping, but its been 3 weeks, almost 4. 
When will this bug get fixed?

**Comment by ThomasWega** [comment]
Hi, I understand. Unfortunately my server is currently not handling explosion damage at all, even on complete vanilla setup. I forwarded this issues to GC and he confirmed it happens. The solution is not as straightforward though. We know what the issue probably is, but we cannot change the code so easily as that would break a ton of other stuff, so we are cautiously testing different solutions.

**Comment by f4a1led** [comment]
> Hi, I understand. Unfortunately my server is currently not handling explosion damage at all, even on complete vanilla setup. I forwarded this issues to GC and he confirmed it happens. The solution is not as straightforward though. We know what the issue probably is, but we cannot change the code so easily as that would break a ton of other stuff, so we are cautiously testing different solutions.

I also understand your statement, but this bug is so annoying. Like, its okay that TNT denies the enchant, but your own plugin's custom effects also deny it. Bleeding, blasting, and etc. My players getting unpatient, and me too. What should I do? Disable TNT on my server, on a server that TNT is useful for destroying defenses, walls?! (Kingdoms)

I also have a feeling, 2 weeks gone, and you did no research about it. I don't want to be rude, but yk I paid for this plugin.

**Comment by ThomasWega** [comment]
> Also I know suggestions and ideas not ment to be sent there. But its realted to Soulbound. My players actually have a nice idea about it. It should has Usage limit. Like you can die with a soulbound enchanted items 3 or 5 items or whatever I give in the config, so after that it gets disenchanted.

This should already be possible by using different soubound levels and removing the enchantment every time and setting it to lower level

**Comment by ThomasWega** [comment]
I was able to fix the explosion issue. Will be available in one of the upcoming updates. I will keep this open for now, and once that update comes out, please re-test it and let me know if there are any more issues. Thank you

**Comment by ThomasWega** [comment]
can you re-test on latest please?

**Comment by f4a1led** [comment]
So its not fixed.
Deaths caused by explosion got fixed, but as I said custom AE effects like: 
- Burn, Bleed, Remove Health, Do Harm still fails KEEP-ON-DEATH. 
I can send video, that my player sent me. (I also tested it)

**Comment by f4a1led** [comment]
https://medal.tv/games/minecraft/clips/kDaZUK5kiocaPXEt6?invite=cr-MSw0MXIsNDE0NDk5MjEy

Here is the link for the video.
My player died because he got killed with a AE Custom enchant that works with DO_HARM. 
But as I said before, we used bleed too, which also kills off KEEP ON DEATH.

**Comment by f4a1led** [comment]
@ThomasWega Sorry for the ping. Can I know an ETA when this can be fixed? 
Cuz I waited 2 months, and its a game breaking bug currently. 

Thanks for your answer in advance !

**Comment by ThomasWega** [comment]
Working on it!

**Comment by ThomasWega** [comment]
@iTzJefeH I have a test version ready. Can you please create a ticket on the discord again and tag me? I'll give you the plugin first to try it out

**Comment by f4a1led** [comment]
> [@iTzJefeH](https://github.com/iTzJefeH) I have a test version ready. Can you please create a ticket on the discord again and tag me? I'll give you the plugin first to try it out

Can you please upload it to Spigot? 
We not installing un-official plugin versions cuz of safety reasons.

**Comment by ThomasWega** [comment]
> > [@iTzJefeH](https://github.com/iTzJefeH) I have a test version ready. Can you please create a ticket on the discord again and tag me? I'll give you the plugin first to try it out
> 
> Can you please upload it to Spigot? We not installing un-official plugin versions cuz of safety reasons.

I can, but I'd rather not because I'd like to get it tested first on someone else's setup. + These changes to pretty core logic usually end up breaking something else in production and then everyone complains and I just cannot test everything alone on my local setup.

**Comment by f4a1led** [comment]
> > > [@iTzJefeH](https://github.com/iTzJefeH) I have a test version ready. Can you please create a ticket on the discord again and tag me? I'll give you the plugin first to try it out
> > 
> > 
> > Can you please upload it to Spigot? We not installing un-official plugin versions cuz of safety reasons.
> 
> I can, but I'd rather not because I'd like to get it tested first on someone else's setup. + These changes to pretty core logic usually end up breaking something else in production and then everyone complains and I just cannot test everything alone on my local setup.

I understand you, but I'm not allowed to do that .

**Comment by ThomasWega** [comment]
Then it might take longer for this to get merged because I need to find someone else to test it in production. Hope you can understand that

**Comment by f4a1led** [comment]
> Then it might take longer for this to get merged because I need to find someone else to test it in production. Hope you can understand that

Maybe, can you upload it into Discord server or Spigot marked as "Unstable build", so we can trust your source and others will know that will be a BETA version too.

**Comment by ThomasWega** [comment]
I cant because the license won't work that way

**Comment by f4a1led** [comment]
> I cant because the license won't work that way
> […](#)
> 
> On Jul 13, 2025 at 11:22 PM +0200, F4a1led ***@***.***>, wrote:
>  iTzJefeH left a comment ([GC-spigot/AdvancedEnchantments#4883](https://github.com/GC-spigot/AdvancedEnchantments/issues/4883))
>  > Then it might take longer for this to get merged because I need to find someone else to test it in production. Hope you can understand that
>  Maybe, can you upload it into Discord server or Spigot marked as "Unstable build", so we can trust your source and others will know that will be a BETA version too.
>  —
>  Reply to this email directly, view it on GitHub, or unsubscribe.
>  You are receiving this because you were mentioned.Message ID: ***@***.***>

Whats the best we can do then? Because I won't download a plugin from a private/dm message.

**Comment by f4a1led** [comment]
Or you can test it too. 
Its so-so-so simple I swear. 

Make an enchant with DO_HARM, LIGTHNING, BLOOD, BURN, REMOVE HEALTH, SPAWN_BLOCKS:<MATERIAL>:<DAMAGE> .

These are the ones that causes players to die with your own AdvanceEnchantments plugin and these are the ones that kill off KEEP_ON_DEATH effect.

**Comment by ThomasWega** [comment]
I've asked you to create a ticket and ping me. You can clearly see I'm a developer on the discord. If you really need I'll get GC (the owner) to send it in the ticket on the server.

**Comment by f4a1led** [comment]
> I've asked you to create a ticket and ping me. You can clearly see I'm a developer on the discord. If you really need I'll get GC (the owner) to send it in the ticket on the server.
> […](#)

I trust you, but since I bought a plugin that stole some datas, I lost my permission to download from private source :|

**Comment by ThomasWega** [comment]
Can you try on latest ver please @iTzJefeH

**Comment by RaftixKun** [comment]
keep on death compatible with angelchest?

**Comment by f4a1led** [comment]
So back there. I created a montage video of the actual bugs. 

- 1+ items with KEEP_ON_DEATH (without any cooldown or chance) won't work at the same time. Only 1 items stays in player's inv.
- Any AE (custom enchant) effect vs KEEP_ON_DEATH doesn't work if the player dies cuz of them. 

Here is the clip: https://medal.tv/games/minecraft/clips/kHLe49p0LNkgbv1zK?invite=cr-MSxybjMsMTg5OTM2ODM1

**Comment by ThomasWega** [comment]
> * 1+ items with KEEP_ON_DEATH (without any cooldown or chance) won't work at the same time. Only 1 items stays in player's inv.

Okay. Managed to fix this pretty easily

**Comment by ThomasWega** [comment]
> * Any AE (custom enchant) effect vs KEEP_ON_DEATH doesn't work if the player dies cuz of them.

Confirmed. Working on a fix. What was fixed in the last version was effects with WAIT and DO_HARM which caused the same issues as well. This instant kill I've missed

**Comment by f4a1led** [comment]
> > * Any AE (custom enchant) effect vs KEEP_ON_DEATH doesn't work if the player dies cuz of them.
> 
> Confirmed. Working on a fix. What was fixed in the last version was effects with WAIT and DO_HARM which caused the same issues as well. This instant kill I've missed

Thanks! But as you can see on my video DO_HARM still doesnt work with it.

**Comment by ThomasWega** [comment]
On one of the next updates this might be fixed. Seems to work fine for me but there might be some other edge cases. I'm already needing to do the worst workarounds for this to even work. Once you see it on the changelog please test it and let me know. You can also ping me in discord but write it mainly here

**Comment by f4a1led** [comment]
> On one of the next updates this might be fixed. Seems to work fine for me but there might be some other edge cases. I'm already needing to do the worst workarounds for this to even work. Once you see it on the changelog please test it and let me know. You can also ping me in discord but write it mainly here

I'm up to downloading un-released versions. So I can test it ASAP. Let me know if its still working for you according to previous talks.

**Comment by ThomasWega** [comment]
> > On one of the next updates this might be fixed. Seems to work fine for me but there might be some other edge cases. I'm already needing to do the worst workarounds for this to even work. Once you see it on the changelog please test it and let me know. You can also ping me in discord but write it mainly here
> 
> I'm up to downloading un-released versions. So I can test it ASAP. Let me know if its still working for you according to previous talks.

Ping me in discord ticket and I'll give you a dev build
