### ISSUE TITLE
Placeholders of display don't parse for the player

### ISSUE THREAD

**Issue by Folas1337** [GC-spigot/AdvancedEnchantments#5062]
### Describe the bug

Using a placeholder in the display of the configuration of the enchantments does not parse for the player but seems to parse for null/nobody.

### How to reproduce

Set up the following part in the enchantments.yml:
```
test1:
  display: "%server_time_YYYY-MM-dd% %player% %player_name% %player player_name% {player} {player player_name} {player name} Test"
  description: Test
  applies-to: All Tools
  group: FABLED
  type: MINING
  applies:
    - ALL_TOOLS
  levels:
    '1':
      effects: {}  
```

Give yourself a book with `/ae givebook <your name here> test1 1 1 100 0` and then apply it in an anvil.
The first placeholder `%server_time_YYYY-MM-dd%` will turn into today's date but all the other placeholders will not be replaced with anything which leads me to believe that any placeholders within the display config section are not parsed for the player but for nobody instead.

### Screenshots / Videos

<img width="1738" height="279" alt="Image" src="https://github.com/user-attachments/assets/b11dd845-102f-4edc-9684-f124f3b42613" />

### "/ae plinfo" link

https://pastes.dev/sTrhKhc6qn

### Server Log

https://mclo.gs/raTIdgP

### Filled out form correct and using latest version

I confirm

**Comment by ThomasWega** [comment]
Should be fixed in the next update. Thanks for reporting

**Comment by Folas1337** [comment]
@ThomasWega I am not sure if I am doing anything wrong but using the exact same steps to reproduce the problem still leads to it not working in version 9.22.6

I am simply putting the tool and the enchantment book in an anvil but the placeholders won't be parsed.

**Comment by ThomasWega** [comment]
> [@ThomasWega](https://github.com/ThomasWega) I am not sure if I am doing anything wrong but using the exact same steps to reproduce the problem still leads to it not working in version 9.22.6
> 
> I am simply putting the tool and the enchantment book in an anvil but the placeholders won't be parsed.

Are you getting yourself new items? Old items won't parse. We parse only on item creation

**Comment by Folas1337** [comment]
> > [@ThomasWega](https://github.com/ThomasWega) I am not sure if I am doing anything wrong but using the exact same steps to reproduce the problem still leads to it not working in version 9.22.6
> > I am simply putting the tool and the enchantment book in an anvil but the placeholders won't be parsed.
> 
> Are you getting yourself new items? Old items won't parse. We parse only on item creation

Yes, I did try new items every time but they still wouldn't work 😦
