### ISSUE TITLE
[BUG] permission effect issue (major issue)

### ISSUE THREAD

**Issue by maxlehot1234** [GC-spigot/AdvancedEnchantments#514]
Hey, 

My players major usebug with permission effect

I create multiple enchants that use permission as effect but here is an example with a part of an enchant.

So inside Autosell plugin I have this:
https://gist.github.com/maxlehot1234/aa8c62ad7b58bd7bb8824f0f454fbf26

Inside enchantments.yml, I have this for asmp1:
https://gist.github.com/maxlehot1234/5f495c5f2acd874bc1868967a04a20e2

So players can simply put their pickaxe in an enderchest and they keep the permission inside LuckPerms
They can now put the pickaxe that was in the enderchest in their inventory by pressing a number on their keyboard.
Lets take "2" for example, so the pickaxe will be put in slot #2 in their inventory.
They can simply go on slot 3 and they keep their multiplier, because AdvancedEnchantments doesn't check permission correctly, so the permission was still apply to the player even if he doesn't have his pickaxe in his hand.

This bug can be much useful than this:
If the player apply asmp1 level 5 on his pickaxe and drop their pickaxe to another player OR simply destroy the pickaxe by put it in ./disposal for example, they still having the multiplier even if they doesn't have the pickaxe, so they can get a new pickaxe with a kit without needed to buy this enchant again.

This part resume ^^^^
So in fact, the permission (effect) apply with the enchant on an item was not removed all the time, so this was used by players to usebug and get the permission effect even if they doesn't have the item in their hand.

If you can fix this, it could be amazing since it could affect a lot of servers that use the permission as effect

BTW, sorry for my bad english, i'm french.

**Comment by maxlehot1234** [comment]
@GC-spigot Here is a video:
https://youtu.be/g4Xo0bGyKzM

Like you can see, when I own the pickaxe that have level 50 on it which in this video was supposed to give Money multiplier : 20.0 (check scoreboard), it give nothing cause of the permission issue.

When I select another inventory slot, I have the multiplier, so player can simply put his pickaxe on an enderchest or in a disposal and he will still get the permission and the money multiplier

**Comment by GC-spigot** [comment]
Fixed.

**Comment by maxlehot1234** [comment]
Still having the same issue with 5.7.4.

Players can get enchants but permission effect apply when they doesn't have the item in-hand which is completly stupid I think.

Are you able to check this part of the plugin?


Thanks again GC

**Comment by maxlehot1234** [comment]
@GC-spigot Why you close it? Still having the same issue..

I apply enchants with eprmission effect on my pickaxe and it apply only when player DOESN'T hold the pickaxe...

That's really bad.

Any way to reopen the issue and fix it please?

**Comment by maxlehot1234** [comment]
Anything on this, still not fixed........ @GC-spigot
